global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:8080', 'spark-worker:8081']

  - job_name: 'model-api'
    static_configs:
      - targets: ['model-api:5000']

  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:8050']

  - job_name: 'rasa'
    static_configs:
      - targets: ['rasa:5005']
